# Generated by Django 4.1.3 on 2022-11-20 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thermometers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('measurement_date', models.DateField(default=datetime.date.today)),
                ('measurement_time', models.TimeField()),
                ('temperature', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=80)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
    ]
