# Generated by Django 4.1.3 on 2022-11-27 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermometer_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thermometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('measurement_date', models.DateField(default=datetime.date.today)),
                ('measurement_time', models.TimeField(default=datetime.datetime.now)),
                ('temperature', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=80)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Thermometers',
        ),
    ]
